name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ src/test_localhost/test_localhost.cpp -I./thirdparty/asio-1.12.1/include -lpthread -o test
    - name: run
      run: ./test
 
